### ISSUE TITLE
[10.0+] purchase_discount performance

### ISSUE THREAD

**Issue by jjscarafia** [OCA/purchase-workflow#503]
Hi @pedrobaeza.

We've detected that aproving PO of many products takes to long and seams to be related to [this line](https://github.com/OCA/purchase-workflow/blob/10.0/purchase_discount/models/purchase_order.py#L87).

Do you remember why that is needed? We have comment it and it works ok. How can you get into an "infinite recursion"?

Just to let you know, we are not using this on v10, instead we have backported some improvements of v10 to v9, so perhups on v10 is not exactly the same but I guess it should be.

**Comment by rousseldenis** [comment]
@pedrobaeza The function '_get_stock_move_price_unit' is incorrectly implemented due to https://github.com/OCA/purchase-workflow/commit/aceb2ebc102fe75f4d13ea1161df50e4bef786c5#diff-05d05bf1b158883e1f78f62e9db20eab

You modify in it fields values. These modifications trigger recompute. You cannot modify values in a 'get' function...

**Comment by pedrobaeza** [comment]
All of this is because Odoo removes our hooks for doing this in a proper way. We can try to get again the hooks, but they are very close in this matter. I tried to do the best for having the correct result (see also #501) with another case that I have detected that is incorrect, but sometimes it has these drawbacks.

**Comment by pedrobaeza** [comment]
Any alternative implementation that works is welcome.

**Comment by rousseldenis** [comment]
@pedrobaeza Sorry but no time for this at this moment

**Comment by jjscarafia** [comment]
Hi @pedrobaeza, thanks for the quickresponse. I completelly understand that is not easy.
About https://github.com/OCA/purchase-workflow/pull/501/files I'm going to test it and comment on the PR, seams good to me and as far as I've tested it doesn't takes to performance issues.

Regarding [setting order state as 'purchase'](https://github.com/OCA/purchase-workflow/blob/10.0/purchase_discount/models/purchase_order.py#L87) I'm not understanding why this is needed. How can you get an "infinite recursion"?
For now I've remove  the "self.order_id.state = 'purchase'" line and the "self.order_id.state = 'draft'" and it goes 5x times faster!! (from 5 minutes to 1) for a big PO.

**Comment by pedrobaeza** [comment]
The state change is because this code:

https://github.com/odoo/odoo/blob/ab60d773eb84a527b3167d7efaf169f70c5c9786/addons/purchase/models/purchase.py#L587

It was triggering continues stock move creation and launching again the price unit query. It seems that it was refactored a year ago in:

https://github.com/odoo/odoo/commit/11f0a5c29fad6ecf71c92e20b0b258fe31da06f8

avoiding this problem, so now it's indeed not needed. Please make a PR removing that state changes.
