### ISSUE TITLE
[9.0] purchase_discount Discounts are not calculated correctly

### ISSUE THREAD

**Issue by mtbochaca** [OCA/purchase-workflow#558]
When I make a purchase order with a discount, it is not calculated correctly. 
Ex: Units: 30 Price: 19.75 Discount: 50% Odoo total line: 296,40 Real total line: 296,25
Tested in runbot. 
http://3328685-9-0-20c98b.runbot2.odoo-community.org/web?debug=1#id=10&view_type=form&model=purchase.order&menu_id=232&action=303

**Comment by pedrobaeza** [comment]
This version might miss some of the patches on 10.0. Please check if it's the case.

**Comment by mtbochaca** [comment]
Not. The problem it's the same in version 10!!!
http://3331579-10-0-9cc0f2.runbot2.odoo-community.org/web?debug=1#id=8&view_type=form&model=purchase.order&menu_id=201&action=302
The problem it's in a rounding method:
Price_unit: 19.75 * discount: 0.5 = 9,875 Rounding (????) = 9,88 * Units = 30 = 296.40
The correct calculation:
Price_unit: 19.75 * discount: 0.5 = 9,875  * Units:30 =  296.25 Rounding here!!!!

I'm working in a code for solve the problem, but I'm not a programing. Sorry

**Comment by legalsylvain** [comment]
Do you use purchase_rounding_method ? Because what you describe is exactly how works this module.

regards.

**Comment by hugosantosred** [comment]
We are experiencing problems with purchase_discount module also in v11.

For example a Purchase Order with one line of a product with a price unit of 23.10 * 50 units and a discount of 1%, the subtotal amount computed for that line is 1143.50

Then validate and invoice the order, the line in the invoice is still the same with 50 units at 23.10 each and a discount of 1% but the computed subtotal amount in this case is 1143.45

So this behaviour is not correct because the amount in the purchase order and in the invoice must be the same.

This seems to be an error with the method that computes the discount in each line, because is using the line.price_unit for store the value of the price_unit with discount, so the amount is rounded to the same decimal positions as the price_unit in the database, losing some precission here

**Comment by pedrobaeza** [comment]
which tax round policy do you have? Can you design a test to be added to the module that proves the problem?

**Comment by hugosantosred** [comment]
@pedrobaeza I've made a PR with the tests for check if the price_subtotal is equal between invoice and purchase.

https://github.com/OCA/purchase-workflow/pull/685
